### ISSUE TITLE
Where to put config?

### ISSUE THREAD

**Issue by axyaxyfr** [rcasula/kostalpiko-homeassistant#14]
Excuse my n00b question, but where do I put the config (example below)

I used this config:
kostal:
host: 192.168.178.135
username: pvserver
password: pvwr
monitored_conditions:
- current_power
- total_energy
- daily_energy
- string1_voltage
- string1_current
- string2_voltage
- string2_current
- l1_voltage
- l1_power
- l2_voltage
- l2_power
- l3_voltage
- l3_power
- status

In a file?

**Comment by petos** [comment]
Hello, 
append this to the ~/config/configuration.yaml
OR
append this line to the configuration.yaml:
```kostal: !include kostal.yaml```
and create ```~/config/kostal.yaml``` and put the rest there:
```    host: !secret kostal_host  # "http://192.168.xx.xx"
    username: !secret kostal_username
    password: !secret kostal_password
    monitored_conditions:
      - current_power
      - total_energy
      - daily_energy
      - string1_voltage
      - string2_voltage
      - string1_current
      - string2_current
      - l1_voltage
      - l1_power
      - l2_voltage
      - l2_power
      - l3_voltage
      - l3_power
      - status
```
