### ISSUE TITLE
Last_reset not supported anymore? 

### ISSUE THREAD

**Issue by cevierix** [rcasula/kostalpiko-homeassistant#18]
Dear rcasula! Seems the latest homeassistant (2022.8.7) there seems to be an issue with "last_reset": 

```
Source: components/sensor/__init__.py:334
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 17:03:37 (1 occurrences)
Last logged: 17:03:37

Entity sensor.kostal_piko_daily_energy (<class 'custom_components.kostal.sensor.PikoSensor'>) with state_class measurement has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom integration author.
```
Best, cevierx

**Comment by jklerkx** [comment]
I think have a related issue. I added daily_energy tomy Energy dashboard, but the energy flowing from my Kostal is not displayed. The sensors give correct readings. 

I have an error in the settings of my Energy Dashboard:
```
Laatste reset ontbreekt
De volgende entiteiten hebben de statusklasse 'measurement', maar 'last_reset' ontbreekt:
sensor.kostal_piko_daily_energy
```

**Comment by jklerkx** [comment]
I seem to have resolved my issue by adding "kostal_piko Total energy" to my dashboard instead of Daily Energy.

**Comment by pergolafabio** [comment]
> I seem to have resolved my issue by adding "kostal_piko Total energy" to my dashboard instead of Daily Energy.

If you add total energy, at what frequention is it added to HA?

**Comment by pergolafabio** [comment]
Hey @rcasula , is it possible to fix the daily sensor with last data, so it can be used in the energy management? I prefer the daily one, because it's also in decimals, gives better values then the total energy sensor
