### ISSUE TITLE
POWER_WATT and other used constants will be deprecated by HA Core 2025.1

### ISSUE THREAD

**Issue by birdie60** [rcasula/kostalpiko-homeassistant#31]
I get deprecated constant warnings in my kostal logs.

`Logger: homeassistant.const
Quelle: helpers/deprecation.py:206
Erstmals aufgetreten: 16:31:21 (6 Vorkommnisse)
Zuletzt protokolliert: 16:31:30

POWER_WATT was used from kostal, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.WATT instead, please report it to the author of the 'kostal' custom integration
ENERGY_KILO_WATT_HOUR was used from kostal, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please report it to the author of the 'kostal' custom integration
ELECTRIC_POTENTIAL_VOLT was used from kostal, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricPotential.VOLT instead, please report it to the author of the 'kostal' custom integration
ELECTRIC_CURRENT_AMPERE was used from kostal, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricCurrent.AMPERE instead, please report it to the author of the 'kostal' custom integration
DEVICE_CLASS_ENERGY was used from kostal, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.ENERGY instead, please report it to the author of the 'kostal' custom integration

Logger: homeassistant.components.sensor
Quelle: helpers/deprecation.py:206
Integration: Sensor (Dokumentation, Probleme)
Erstmals aufgetreten: 16:31:30 (4 Vorkommnisse)
Zuletzt protokolliert: 16:31:30

STATE_CLASS_MEASUREMENT was used from kostal, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.MEASUREMENT instead, please report it to the author of the 'kostal' custom integration
STATE_CLASS_TOTAL_INCREASING was used from kostal, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.TOTAL_INCREASING instead, please report it to the author of the 'kostal' custom integration`

**Comment by luckysession** [comment]
Same here!

**Comment by birdie60** [comment]
Can anyone pls look into this issue and solve it maybe, as HA Core 2025.1 is not so far away!
