### ISSUE TITLE
Missing yaml config sample

### ISSUE THREAD

**Issue by lucdiniz** [rcasula/kostalpiko-homeassistant#4]
Hi, Can you share config file.
Tried this one, but fails.
Many Thanks

sensor:
  - platform: kostal
    host: !secret kostal_host  # "http://192.168.xx.xx"
    username: !secret kostal_username
    password: !secret kostal_password
    monitored_conditions:
      - solar_generator_power  # only available when using a BA sensor
      - consumption_phase_1    # only available when using a BA sensor
      - consumption_phase_2    # only available when using a BA sensor
      - consumption_phase_3    # only available when using a BA sensor
      - current_power
      - total_energy
      - daily_energy
      - string1_voltage
      - string1_current
      - string2_voltage
      - string2_current
      - l1_voltage
      - l1_power
      - l2_voltage
      - l2_power
      - l3_voltage
      - l3_power
      - status

**Comment by rcasula** [comment]
Because it is not a sensor. This configuration should be put on the configuration.yaml root.

**Comment by lucdiniz** [comment]
Many thanks.
Working with this configs:

kostal:
  host: !secret kostal_host  # "http://192.168.xx.xx"
  username: !secret kostal_username
  password: !secret kostal_password
  monitored_conditions:
    - solar_generator_power  # only available when using a BA sensor
    - consumption_phase_1    # only available when using a BA sensor
    - consumption_phase_2    # only available when using a BA sensor
    - consumption_phase_3    # only available when using a BA sensor
    - current_power
    - total_energy
    - daily_energy
    - string1_voltage
    - string1_current
    - string2_voltage
    - string2_current
    - l1_voltage
    - l1_power
    - l2_voltage
    - l2_power
    - l3_voltage
    - l3_power
    - status
