### ISSUE TITLE
Setting last_reset for entities with state_class other than 'total' is deprecated

### ISSUE THREAD

**Issue by pergolafabio** [rcasula/kostalpiko-homeassistant#7]
Hey @rcasula,

i also receive warning below, are you able to fix it?

thnx

`WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.kostal_piko_daily_energy (<class 'custom_components.kostal.sensor.PikoSensor'>) with state_class measurement has set last_reset. Setting last_reset for entities with state_class other than 'total' is deprecated and will be removed from Home Assistant Core 2021.11. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.`

**Comment by rcasula** [comment]
I think it is resolved now. Could you please check?

**Comment by pergolafabio** [comment]
yes indeed
